name: RDP Windows 12 Jam

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 720  # 12 jam
    steps:
      - name: Aktifkan RDP & Firewall
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          echo "✅ RDP Telah Diaktifkan!"

      - name: Tampilkan Info Login
        run: |
          whoami
          hostname
          ipconfig
          echo "📌 Username: runneradmin"
          echo "📌 Password default GitHub Actions tidak bisa diubah"
          echo "Silakan connect ke IP Public dari log menggunakan Remote Desktop (mstsc)"
          echo "📢 Catatan: RDP akan mati otomatis setelah 12 jam."

      - name: Tahan Selama 12 Jam
        run: |
          Start-Sleep -Seconds 43200  # 12 jam
