name: RDP with Ngrok (12 jam)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 720  # 12 jam
    steps:
      - name: Set user password
        run: |
          net user runneradmin MyRdpPass123
          echo "Password runneradmin diubah"

      - name: Aktifkan RDP dan Firewall
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Download & Start Ngrok (for RDP)
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath .
          .\ngrok\ngrok.exe config add-authtoken 2dHpUQv2XsW8Se0LHY2WH31LwtH_4kiGSnvEnRUnuz7EZQL3A
          Start-Process .\ngrok\ngrok.exe "tcp 3389"
          echo "Ngrok started on port 3389"
          Start-Sleep -Seconds 43200
